const userData = [
	{
		content: [
			{
				id:1,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:true,
				total:99
			},{
				id:2,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:false,
				total:99
			},{
				id:3,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:false,
				total:99
			},{
				id:4,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu4.png',
				isSide:true,
				total:99
			},{
				id:5,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu5.png',
				isSide:false,
				total:99
			},{
				id:6,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu6.png',
				isSide:false,
				total:99
			},{
				id:7,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu7.png',
				isSide:true,
				total:99
			},{
				id:8,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:false,
				total:99
			},{
				id:9,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:true,
				total:99
			},{
				id:10,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:true,
				total:99
			},{
				id:11,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu4.png',
				isSide:true,
				total:99
			},{
				id:12,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu5.png',
				isSide:true,
				total:99
			}
		]
	}, 
	{
		content: [
			{
				id:1,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:true,
				total:99
			},{
				id:2,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:false,
				total:99
			},{
				id:3,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:false,
				total:99
			},{
				id:4,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu4.png',
				isSide:true,
				total:99
			},{
				id:5,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu5.png',
				isSide:false,
				total:99
			},{
				id:6,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu6.png',
				isSide:false,
				total:99
			},{
				id:7,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu7.png',
				isSide:true,
				total:99
			},{
				id:8,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:false,
				total:99
			},{
				id:9,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:true,
				total:99
			},{
				id:10,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:true,
				total:99
			},{
				id:11,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu4.png',
				isSide:true,
				total:99
			},{
				id:12,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu5.png',
				isSide:true,
				total:99
			}
		]
	}, 
	{
		content: [
			{
				id:1,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:true,
				total:99
			},{
				id:2,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:false,
				total:99
			},{
				id:3,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:false,
				total:99
			},{
				id:4,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu4.png',
				isSide:true,
				total:99
			},{
				id:5,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu5.png',
				isSide:false,
				total:99
			},{
				id:6,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu6.png',
				isSide:false,
				total:99
			},{
				id:7,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu7.png',
				isSide:true,
				total:99
			},{
				id:8,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:false,
				total:99
			},{
				id:9,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:true,
				total:99
			},{
				id:10,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:true,
				total:99
			},null,null
		]
	},
]

const tableList = {
	tableRight:[
		{
			id:1,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			number:234,
			isShadow:false
		},{
			id:2,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			number:16,
			isShadow:true
		},{
			id:3,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			number:16,
			isShadow:true
		},{
			id:4,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			number:16,
			isShadow:true
		}
	],
	tableLeft:[
		{
			id:1,
			tabelNumber:712,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			users:[
				{
					userId:1,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:false
				},{
					userId:2,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:true
				},{
					userId:3,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:true
				},{
					userId:4,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:false
				},{
					userId:1,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:false
				},{
					userId:2,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:true
				},{
					userId:3,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:true
				},{
					userId:4,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:false
				}
			]
		},{
			id:2,
			tabelNumber:58,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			users:[
				{
					userId:1,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:false
				},{
					userId:2,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:true
				},{
					userId:3,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:true
				},{
					userId:1,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:false
				},{
					userId:2,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:true
				},{
					userId:3,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:true
				},{
					userId:4,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:false
				},{
					userId:1,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:false
				},{
					userId:2,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:true
				},{
					userId:3,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:true
				},{
					userId:4,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:false
				}
			]
		},{
			id:3,
			tabelNumber:699,
			tabelUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tableBG.png',
			users:[
				{
					userId:1,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:false
				},{
					userId:2,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user2.png',
					isShadow:true
				},{
					userId:3,
					userUrl:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/user1.png',
					isShadow:true
				}
			]
		}
		
	]
}


const userData1 = [
	{
		content: [
			{
				id:1,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu7.png',
				isSide:true,
				total:99
			},{
				id:2,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu6.png',
				isSide:false,
				total:99
			},{
				id:3,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu5.png',
				isSide:false,
				total:99
			},{
				id:4,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu4.png',
				isSide:true,
				total:99
			},{
				id:5,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:false,
				total:99
			},{
				id:6,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu2.png',
				isSide:false,
				total:99
			},{
				id:7,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu1.png',
				isSide:true,
				total:99
			},{
				id:8,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu6.png',
				isSide:false,
				total:99
			},{
				id:9,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu7.png',
				isSide:true,
				total:99
			},{
				id:10,
				src:'http://lilian007.oss-cn-shanghai.aliyuncs.com/mbm/MBMimg/pages/users/tu3.png',
				isSide:true,
				total:99
			},null,null
		]
	},
]

export { userData,tableList,userData1 }